Traceback (most recent call last):
  File "/u/mbanisharifdehkordi/Github/IOR_Benchmark/scripts/parse_darshan_dir.py", line 101, in <module>
    main()
  File "/u/mbanisharifdehkordi/Github/IOR_Benchmark/scripts/parse_darshan_dir.py", line 97, in main
    df.to_csv(args.output_csv, index=False)
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/core/generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/u/mbanisharifdehkordi/.conda/envs/ior_env/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
